language: ruby
rvm:
  - "2.3.8"
  - "2.4.2"
cache: bundler
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

gemfile:
  - gemfiles/activesupport5.gemfile
  - gemfiles/activesupport4.gemfile
